### ISSUE TITLE
update frequency/latency of ERA5

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/ds-raster-pipelines#31]
in era5 readme it says:

https://github.com/OCHA-DAP/ds-raster-pipelines/blob/e13e50c76f4fcb043de9f11a3182466a8a3fcc6f/src/era5/README.md?plain=1#L101

I find this latency surprising as GEE produces ERA5 precip COGS that are available with a latency of ~10 days

**Comment by hannahker** [comment]
@zackarno is it surprising that this latency is less than GEE? I've got this latency here based on the ECMWF docs.

**Comment by zackarno** [comment]
What I mean is that if we only get the updates on the 5th or 6th of every month it seems there will be a big lag between current date and latest data.

Right now, 2024 Sep 16, if I look at ERA5 on GEE I can get daily data up to Sep 9. Seems like we should be able to keep the dat updating on a daily rolling basis rather than 1x per month?

**Comment by hannahker** [comment]
Oh we just have ERA5 monthly data for now!

**Comment by zackarno** [comment]
got it! I was thinking we were doing monthly
