### ISSUE TITLE
FloodScan  - Will we combine MFED & SFED?

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/ds-raster-pipelines#42]
Thought it would be good to document/discuss if we will combine SFED & MFED bands into the single daily raster tifs. We had initially thought it would be a nice way to simplify the data storage and allow for easier comparisons of SFED and MFED. However, if it complicates the pipeline or there are other advantages to keeping them separate it could also be fine

**Comment by isatotun** [comment]
We talked about the effort around doing this and how it would mean adding more duplicated data to the container as we are already saving separate files for MFED and SFED so for now we will not combine.

**Comment by zackarno** [comment]
im not sure why merging SFED & MFED would mean duplicated data - because you could just merge SFED and MFED as an initially processing step straight from the zip files. I feel like `xarray` is very well suited to handle this type of merge? I do agree though that if for some reason it is too much work  it's not a big deal to skip

**Comment by isatotun** [comment]
The files are now combined.
